#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="${BASEDIR}/dotfiles"

# vim
ln -fs ${DOTFILES_DIR}/.vimrc ~/.vimrc

# git
ln -fs ${DOTFILES_DIR}/.gitconfig ~/.gitconfig

