#!/bin/bash

# Update App Store apps
sudo softwareupdate -i -a

# Install xcode command line
xcode-select --install

# Install Homebrew and Homebrew-Cask
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew tap caskroom/cask

brew install brew-cask
brew tap caskroom/versions

# Update Homebrew
brew update
brew upgrade

# Ctags for vim
brew install ctags

# Create symlinks for dotfiles
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="${BASEDIR}/dotfiles"

ln -fsv ${DOTFILES_DIR}/.vimrc ~

ln -fsv ${DOTFILES_DIR}/.ctags ~

ln -fsv ${BASEDIR}/gitkurwa/config ~/.gitkurwa_config
ln -fsv ${DOTFILES_DIR}/.gitconfig ~
ln -fsv ${DOTFILES_DIR}/.gitignore ~
ln -fsv ${DOTFILES_DIR}/.gitconfig_local ~

